import type { ComponentType, CSSProperties } from "react";
import {
  CinemaEditorial,
  ContactSheet,
  EditorialClassic,
  EightBit,
  FashionEditorial,
  Graphite,
  IvoryIndex,
  MusicEditorial,
  PressKit,
  Stardust,
  StudioWindow,
  Sidecar,
  DesktopDaydream,
  GalleryOne,
  Monograph,
  ContactGrid,
  MosaicArchive,
  Canvas,
  Storyboard,
  Notebook,
  Signals,
  PortfolioSplit,
  Orbit,
  InfiniteDesk,
  MemoryWall,
  SplitReality,
  TerminalDream,
} from "../profile-experiences/experiences";
import type { ExperienceProps } from "../profile-experiences/shared";

export type ThemeLayout = "editorial" | "grid" | "cinematic" | "desktop" | "sidebar" | "press";
export type MusicPlacement = "inline" | "compact" | "card" | "floating" | "sidebar" | "hero";
export type EditorialCategory = "Editorial" | "Fashion" | "Music" | "Cinema" | "Portfolio" | "Archive" | "Experimental" | "Creator";

export type PlaygroundTheme = {
  id: string;
  name: string;
  description: string;
  category: EditorialCategory;
  order: number;
  featured?: boolean;
  layout: ThemeLayout;
  musicPlacement: MusicPlacement;
  className: string;
  component: ComponentType<ExperienceProps>;
  colors: {
    background: string;
    surface: string;
    foreground: string;
    muted: string;
    accent: string;
    border: string;
  };
  radius: string;
  headingFont: string;
  bodyFont: string;
  contentWidth: string;
};

export const DEFAULT_THEME_ID = "ivory-index";

const editorialRegistry = [
{
    id: "editorial-classic",
    name: "Editorial Classic",
    description: "A timeless magazine profile with a formal masthead, cover portrait, pull quote, listening room, and selected archive.",
    category: "Editorial",
    order: 5,
    featured: true,
    layout: "editorial",
    musicPlacement: "card",
    className: "theme-editorial-classic",
    component: EditorialClassic,
    colors: {
      background: "#eee9df",
      surface: "#f8f4ec",
      foreground: "#171512",
      muted: "#706a61",
      accent: "#8b2323",
      border: "rgba(23, 21, 18, 0.22)",
    },
    radius: "0px",
    headingFont: 'Georgia, "Times New Roman", serif',
    bodyFont: '"Helvetica Neue", Arial, sans-serif',
    contentWidth: "1440px",
  },

  { id:"ivory-index", name:"Ivory Index", description:"Warm editorial whitespace and a restrained inline player.", category:"Editorial", order:10, featured:true, layout:"editorial", musicPlacement:"inline", className:"theme-ivory-index", component:IvoryIndex, colors:{background:"#f3efe6",surface:"#faf7f0",foreground:"#1e1c18",muted:"#7d756a",accent:"#9b2f25",border:"rgba(30, 28, 24, 0.18)"}, radius:"2px", headingFont:'Georgia, "Times New Roman", serif', bodyFont:'Georgia, "Times New Roman", serif', contentWidth:"980px" },
  { id:"cinema-editorial", name:"Cinema Editorial", description:"Oversized type, portrait-led storytelling, pull quotes, and film-journal pacing.", category:"Cinema", order:20, featured:true, layout:"editorial", musicPlacement:"hero", className:"theme-cinema-editorial", component:CinemaEditorial, colors:{background:"#f3f0e8",surface:"#ffffff",foreground:"#111111",muted:"#77736b",accent:"#9c241f",border:"rgba(17, 17, 17, 0.22)"}, radius:"0px", headingFont:'"Arial Narrow", "Helvetica Neue", Arial, sans-serif', bodyFont:'"Helvetica Neue", Arial, sans-serif', contentWidth:"1440px" },
  { id:"fashion-editorial", name:"Fashion Editorial", description:"Refined serif typography, asymmetrical portrait layouts, and campaign pacing.", category:"Fashion", order:30, featured:true, layout:"editorial", musicPlacement:"card", className:"theme-fashion-editorial", component:FashionEditorial, colors:{background:"#f7f5f0",surface:"#ffffff",foreground:"#111111",muted:"#76716a",accent:"#8b1f2d",border:"rgba(17, 17, 17, 0.18)"}, radius:"0px", headingFont:'Georgia, "Times New Roman", serif', bodyFont:'"Helvetica Neue", Arial, sans-serif', contentWidth:"1440px" },
  { id:"music-editorial", name:"Music Editorial", description:"A bold cover story, featured release, pull quote, visual sequence, and artist archive.", category:"Music", order:40, featured:true, layout:"editorial", musicPlacement:"hero", className:"theme-music-editorial", component:MusicEditorial, colors:{background:"#0d0d0d",surface:"#171717",foreground:"#f2efe7",muted:"#9a978f",accent:"#d9ff4b",border:"rgba(242, 239, 231, 0.18)"}, radius:"0px", headingFont:'"Helvetica Neue", Arial, sans-serif', bodyFont:'"Helvetica Neue", Arial, sans-serif', contentWidth:"1440px" },
  { id:"contact-sheet", name:"Contact Sheet", description:"A photography-first grid with a compact utility player.", category:"Portfolio", order:50, layout:"grid", musicPlacement:"compact", className:"theme-contact-sheet", component:ContactSheet, colors:{background:"#eeeeea",surface:"#ffffff",foreground:"#151515",muted:"#6f6f68",accent:"#ff4e00",border:"rgba(21, 21, 21, 0.24)"}, radius:"0px", headingFont:'"Helvetica Neue", Arial, sans-serif', bodyFont:'"Courier New", monospace', contentWidth:"1240px" },
  { id:"graphite", name:"Graphite", description:"Layered black panels with a dedicated music card.", category:"Editorial", order:60, layout:"cinematic", musicPlacement:"card", className:"theme-graphite", component:Graphite, colors:{background:"#101010",surface:"#1a1a1a",foreground:"#f1eee8",muted:"#96928b",accent:"#e6a23c",border:"rgba(255, 255, 255, 0.12)"}, radius:"18px", headingFont:'Georgia, "Times New Roman", serif', bodyFont:'"Helvetica Neue", Arial, sans-serif', contentWidth:"1120px" },
  { id:"press-kit", name:"Press Kit", description:"An artist-facing hero layout with prominent music.", category:"Music", order:70, layout:"press", musicPlacement:"hero", className:"theme-press-kit", component:PressKit, colors:{background:"#0c0c0d",surface:"#151517",foreground:"#ffffff",muted:"#a0a0a6",accent:"#fff200",border:"rgba(255, 255, 255, 0.14)"}, radius:"24px", headingFont:'"Helvetica Neue", Arial, sans-serif', bodyFont:'"Helvetica Neue", Arial, sans-serif', contentWidth:"1180px" },
  { id:"stardust", name:"Stardust", description:"A dreamy sidebar profile with music living in the rail.", category:"Archive", order:80, layout:"sidebar", musicPlacement:"sidebar", className:"theme-stardust", component:Stardust, colors:{background:"#17142a",surface:"#211d38",foreground:"#f6efff",muted:"#b8add0",accent:"#c59cff",border:"rgba(197, 156, 255, 0.35)"}, radius:"18px", headingFont:'Georgia, "Times New Roman", serif', bodyFont:'"Helvetica Neue", Arial, sans-serif', contentWidth:"1160px" },
  { id:"eight-bit", name:"Eight Bit", description:"A nostalgic windowed profile with a floating player.", category:"Archive", order:90, layout:"desktop", musicPlacement:"floating", className:"theme-eight-bit", component:EightBit, colors:{background:"#f2dce6",surface:"#fff8fc",foreground:"#493746",muted:"#8b657c",accent:"#c73f7c",border:"#9f4d78"}, radius:"14px", headingFont:'"Courier New", monospace', bodyFont:'"Courier New", monospace', contentWidth:"1040px" },

  {
    id: "studio-window",
    name: "Studio Window",
    description: "A floating browser-like portfolio with a quiet profile rail and spacious work surface.",
    category: "Portfolio",
    order: 100,
    featured: true,
    layout: "sidebar",
    musicPlacement: "floating",
    className: "theme-studio-window",
    component: StudioWindow,
    colors: { background: "#202022", surface: "#ffffff", foreground: "#171717", muted: "#767676", accent: "#d9ff4b", border: "rgba(17,17,17,.16)" },
    radius: "10px",
    headingFont: 'Georgia, "Times New Roman", serif',
    bodyFont: '"Helvetica Neue", Arial, sans-serif',
    contentWidth: "1180px",
  },
  {
    id: "sidecar",
    name: "Sidecar",
    description: "A strict vertical identity rail paired with a generous editorial image canvas.",
    category: "Portfolio",
    order: 110,
    featured: true,
    layout: "sidebar",
    musicPlacement: "floating",
    className: "theme-sidecar",
    component: Sidecar,
    colors: { background: "#f7f7f3", surface: "#ffffff", foreground: "#111111", muted: "#777777", accent: "#111111", border: "rgba(17,17,17,.15)" },
    radius: "0px",
    headingFont: '"Helvetica Neue", Arial, sans-serif',
    bodyFont: '"Helvetica Neue", Arial, sans-serif',
    contentWidth: "1440px",
  },
  {
    id: "desktop-daydream",
    name: "Desktop Daydream",
    description: "A soft retro workspace made from independent profile, sound, and archive windows.",
    category: "Experimental",
    order: 120,
    featured: true,
    layout: "desktop",
    musicPlacement: "floating",
    className: "theme-desktop-daydream",
    component: DesktopDaydream,
    colors: { background: "#eee5d3", surface: "#f8f0dc", foreground: "#315b61", muted: "#6f8c8f", accent: "#7ea8a6", border: "#7ea8a6" },
    radius: "0px",
    headingFont: '"Courier New", monospace',
    bodyFont: '"Courier New", monospace',
    contentWidth: "1200px",
  },

  {
    id: "gallery-one",
    name: "Gallery One",
    description: "An oversized portrait-led portfolio with restrained navigation and generous editorial spacing.",
    category: "Editorial",
    order: 130,
    featured: true,
    layout: "editorial",
    musicPlacement: "floating",
    className: "theme-gallery-one",
    component: GalleryOne,
    colors: {
      background: "#f4f1e9",
      surface: "#fbfaf6",
      foreground: "#151515",
      muted: "#706d66",
      accent: "#151515",
      border: "rgba(21,21,21,.18)",
    },
    radius: "0px",
    headingFont: 'Georgia, "Times New Roman", serif',
    bodyFont: '"Helvetica Neue", Arial, sans-serif',
    contentWidth: "1380px",
  },
  {
    id: "monograph",
    name: "Monograph",
    description: "A numbered publication layout built around serif typography, wide margins, and archival pacing.",
    category: "Editorial",
    order: 140,
    featured: true,
    layout: "editorial",
    musicPlacement: "inline",
    className: "theme-monograph",
    component: Monograph,
    colors: {
      background: "#e9e5dc",
      surface: "#f7f3ea",
      foreground: "#191816",
      muted: "#767067",
      accent: "#8b2f25",
      border: "rgba(25,24,22,.22)",
    },
    radius: "0px",
    headingFont: 'Georgia, "Times New Roman", serif',
    bodyFont: 'Georgia, "Times New Roman", serif',
    contentWidth: "1240px",
  },
  {
    id: "contact-grid",
    name: "Contact Grid",
    description: "A compact identity rail paired with a dense image-forward archive inspired by contact sheets.",
    category: "Archive",
    order: 150,
    featured: true,
    layout: "grid",
    musicPlacement: "sidebar",
    className: "theme-contact-grid",
    component: ContactGrid,
    colors: {
      background: "#ecebe6",
      surface: "#f7f6f1",
      foreground: "#111111",
      muted: "#72716d",
      accent: "#111111",
      border: "rgba(17,17,17,.2)",
    },
    radius: "0px",
    headingFont: '"Helvetica Neue", Arial, sans-serif',
    bodyFont: '"Helvetica Neue", Arial, sans-serif',
    contentWidth: "1480px",
  },
  {
    id: "mosaic-archive",
    name: "Mosaic Archive",
    description: "An asymmetric portfolio archive with a compact identity header and flexible masonry rhythm.",
    category: "Portfolio",
    order: 160,
    featured: true,
    layout: "grid",
    musicPlacement: "floating",
    className: "theme-mosaic-archive",
    component: MosaicArchive,
    colors: {
      background: "#f0eee8",
      surface: "#faf8f2",
      foreground: "#181818",
      muted: "#77736c",
      accent: "#315d5a",
      border: "rgba(24,24,24,.16)",
    },
    radius: "2px",
    headingFont: '"Helvetica Neue", Arial, sans-serif',
    bodyFont: '"Helvetica Neue", Arial, sans-serif',
    contentWidth: "1420px",
  },

  {
    id: "canvas",
    name: "Canvas",
    description: "A portrait-led creator page with floating identity details and a minimal exhibition rhythm.",
    category: "Creator",
    order: 170,
    featured: true,
    layout: "editorial",
    musicPlacement: "floating",
    className: "theme-canvas",
    component: Canvas,
    colors: {
      background: "#dedbd3",
      surface: "#f4f1ea",
      foreground: "#151515",
      muted: "#6e6a62",
      accent: "#bd3f2d",
      border: "rgba(21,21,21,.2)",
    },
    radius: "2px",
    headingFont: '"Helvetica Neue", Arial, sans-serif',
    bodyFont: '"Helvetica Neue", Arial, sans-serif',
    contentWidth: "1480px",
  },
  {
    id: "storyboard",
    name: "Storyboard",
    description: "A cinematic creator profile framed as scenes, takes, and a continuous visual production timeline.",
    category: "Creator",
    order: 180,
    featured: true,
    layout: "cinematic",
    musicPlacement: "compact",
    className: "theme-storyboard",
    component: Storyboard,
    colors: {
      background: "#151515",
      surface: "#202020",
      foreground: "#f4f1e9",
      muted: "#a9a49b",
      accent: "#e16d3f",
      border: "rgba(244,241,233,.2)",
    },
    radius: "0px",
    headingFont: '"Helvetica Neue", Arial, sans-serif',
    bodyFont: '"Helvetica Neue", Arial, sans-serif',
    contentWidth: "1500px",
  },
  {
    id: "notebook",
    name: "Notebook",
    description: "A tactile journal-style profile for sketches, field notes, photographs, and unfinished ideas.",
    category: "Creator",
    order: 190,
    featured: true,
    layout: "editorial",
    musicPlacement: "inline",
    className: "theme-notebook",
    component: Notebook,
    colors: {
      background: "#d9d1bd",
      surface: "#f2ead7",
      foreground: "#29251f",
      muted: "#756c5f",
      accent: "#375f8b",
      border: "rgba(41,37,31,.22)",
    },
    radius: "3px",
    headingFont: 'Georgia, "Times New Roman", serif',
    bodyFont: 'Georgia, "Times New Roman", serif',
    contentWidth: "1180px",
  },
  {
    id: "signals",
    name: "Signals",
    description: "A music-first creator profile with a live-frequency identity, waveform details, and transmission archive.",
    category: "Creator",
    order: 200,
    featured: true,
    layout: "cinematic",
    musicPlacement: "hero",
    className: "theme-signals",
    component: Signals,
    colors: {
      background: "#111512",
      surface: "#1b211c",
      foreground: "#e9f0df",
      muted: "#9aa593",
      accent: "#b8ff4f",
      border: "rgba(184,255,79,.24)",
    },
    radius: "0px",
    headingFont: '"Helvetica Neue", Arial, sans-serif',
    bodyFont: '"Helvetica Neue", Arial, sans-serif',
    contentWidth: "1420px",
  },
  {
    id: "portfolio-split",
    name: "Portfolio Split",
    description: "A fixed creator identity panel paired with an expansive project feed for focused portfolio presentation.",
    category: "Creator",
    order: 210,
    featured: true,
    layout: "sidebar",
    musicPlacement: "sidebar",
    className: "theme-portfolio-split",
    component: PortfolioSplit,
    colors: {
      background: "#efeee9",
      surface: "#faf9f5",
      foreground: "#171717",
      muted: "#706f69",
      accent: "#2a4b7c",
      border: "rgba(23,23,23,.18)",
    },
    radius: "0px",
    headingFont: '"Helvetica Neue", Arial, sans-serif',
    bodyFont: '"Helvetica Neue", Arial, sans-serif',
    contentWidth: "1520px",
  },

  {
    id: "orbit",
    name: "Orbit",
    description: "A celestial profile system with layered rings, moving nodes, and an identity suspended at the center.",
    category: "Experimental",
    order: 220,
    featured: true,
    layout: "cinematic",
    musicPlacement: "floating",
    className: "theme-orbit",
    component: Orbit,
    colors: {
      background: "#090b13",
      surface: "#151a2a",
      foreground: "#edf0ff",
      muted: "#8d95b5",
      accent: "#8e7cff",
      border: "rgba(142,124,255,.28)",
    },
    radius: "999px",
    headingFont: '"Helvetica Neue", Arial, sans-serif',
    bodyFont: '"Helvetica Neue", Arial, sans-serif',
    contentWidth: "1500px",
  },
  {
    id: "infinite-desk",
    name: "Infinite Desk",
    description: "A desktop-world profile composed from floating windows, notes, signals, and workspace fragments.",
    category: "Experimental",
    order: 230,
    featured: true,
    layout: "desktop",
    musicPlacement: "floating",
    className: "theme-infinite-desk",
    component: InfiniteDesk,
    colors: {
      background: "#c9d1d8",
      surface: "#eef1f4",
      foreground: "#18202a",
      muted: "#647180",
      accent: "#306fd6",
      border: "rgba(24,32,42,.24)",
    },
    radius: "10px",
    headingFont: '"Helvetica Neue", Arial, sans-serif',
    bodyFont: '"Helvetica Neue", Arial, sans-serif',
    contentWidth: "1500px",
  },
  {
    id: "memory-wall",
    name: "Memory Wall",
    description: "A tactile archive of images, notes, tape marks, and fragments arranged like a private evidence wall.",
    category: "Experimental",
    order: 240,
    featured: true,
    layout: "editorial",
    musicPlacement: "inline",
    className: "theme-memory-wall",
    component: MemoryWall,
    colors: {
      background: "#b8aa8d",
      surface: "#e8dfc9",
      foreground: "#2a251d",
      muted: "#736a5a",
      accent: "#9d3f32",
      border: "rgba(42,37,29,.25)",
    },
    radius: "2px",
    headingFont: 'Georgia, "Times New Roman", serif',
    bodyFont: '"Courier New", monospace',
    contentWidth: "1380px",
  },
  {
    id: "split-reality",
    name: "Split Reality",
    description: "A dual-state profile that places the public self and its abstract echo on opposite sides of one world.",
    category: "Experimental",
    order: 250,
    featured: true,
    layout: "sidebar",
    musicPlacement: "floating",
    className: "theme-split-reality",
    component: SplitReality,
    colors: {
      background: "#e9e6de",
      surface: "#f7f4ed",
      foreground: "#161616",
      muted: "#716d66",
      accent: "#e84c3d",
      border: "rgba(22,22,22,.2)",
    },
    radius: "0px",
    headingFont: '"Helvetica Neue", Arial, sans-serif',
    bodyFont: '"Helvetica Neue", Arial, sans-serif',
    contentWidth: "1600px",
  },
  {
    id: "terminal-dream",
    name: "Terminal Dream",
    description: "A luminous terminal interface where identity, music, and posts appear as a living system session.",
    category: "Experimental",
    order: 260,
    featured: true,
    layout: "desktop",
    musicPlacement: "floating",
    className: "theme-terminal-dream",
    component: TerminalDream,
    colors: {
      background: "#030806",
      surface: "#07130d",
      foreground: "#b8ffd2",
      muted: "#55936c",
      accent: "#42ff87",
      border: "rgba(66,255,135,.27)",
    },
    radius: "0px",
    headingFont: '"Courier New", monospace',
    bodyFont: '"Courier New", monospace',
    contentWidth: "1460px",
  },
] satisfies PlaygroundTheme[];

export const playgroundThemes: PlaygroundTheme[] =
  [...editorialRegistry].sort((a, b) => a.order - b.order);

export function getTheme(themeId?: string): PlaygroundTheme {
  return playgroundThemes.find((theme) => theme.id === themeId)
    ?? playgroundThemes.find((theme) => theme.id === DEFAULT_THEME_ID)
    ?? playgroundThemes[0];
}

export type ThemeStyle = CSSProperties & Record<`--pg-${string}`, string>;
export function getThemeStyle(theme: PlaygroundTheme): ThemeStyle {
  return {
    "--pg-background": theme.colors.background,
    "--pg-surface": theme.colors.surface,
    "--pg-foreground": theme.colors.foreground,
    "--pg-muted": theme.colors.muted,
    "--pg-accent": theme.colors.accent,
    "--pg-border": theme.colors.border,
    "--pg-radius": theme.radius,
    "--pg-heading-font": theme.headingFont,
    "--pg-body-font": theme.bodyFont,
    "--pg-content-width": theme.contentWidth,
  };
}
